update: update-docs update-api

update-docs:
	@echo "Updating Rebel Documentation translations."
	@cd docs && make update

update-api:
	@echo "Update Rebel Engine API translations."
	@cd api && make update
