update: update-docs update-api

update-docs:
	@echo "Updating Rebel Documentation translations."
	@cd docs && make --no-print-directory update

update-api:
	@echo "Updating Rebel Engine API translations."
	@cd api && make --no-print-directory update
